- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      dnf: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/repository.yml
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/gnome.yml

  

