user_name: bejohnson

- name: Install python3-psutil package
  dnf: name=python3-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/{{ user_name }}/.wallpaper.jpg owner={{ user_name }} group={{ user_name }} mode=600

- name: Set GNOME Wallpaper
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ user_name }}/.wallpaper.jpg'"

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest=/home/{{ user_name }}/.lockscreen.jpg owner={{ user_name }} group={{ user_name }} mode=600

- name: Set lock screen background
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/{{ user_name }}/.lockscreen.jpg'"

- name: Install arc theme
  dnf: name=arc-theme

- name: Set GTK theme
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc-Dark'"

- name: Install papirus-icon theme
  dnf: name=papirus-icon-theme

- name: Set GTK theme
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/interface/icon-theme" value="'Papirus-Light'"

- name: Set clock format
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/interface/clock-format" value="'12h'"

- name: Set clock day format on
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/interface/clock-show-weekday" value="'True'"

- name: Set clock show date off
  become_user: {{ user_name }}
  dconf: key="/org/gnome/desktop/interface/clock-show-date" value="'False'"