- name: Install python3-psutil package
  dnf: name=python3-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/bejohnson/.wallpaper.jpg owner=bejohnson group=bejohnson mode=600

- name: Set GNOME Wallpaper
  become_user: bejohnson
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/bejohnson/.wallpaper.jpg'"

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest=/home/bejohnson/.lockscreen.jpg owner=bejohnson group=bejohnson mode=600

- name: Set lock screen background
  become_user: bejohnson
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/bejohnson/.lockscreen.jpg'"

- name: Install arc theme
  dnf: name=arc-theme

- name: Set GTK theme
  become_user: bejohnson
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc-Dark'"

- name: Install papirus-icon theme
  dnf: name=papirus-icon-theme

- name: Set GTK theme
  become_user: bejohnson
  dconf: key="/org/gnome/desktop/interface/icon-theme" value="'Papirus-Light'"

- name: Sset clock format
  become_user: bejohnson
  dconf: key="/org/gnome/desktop/interface/clock-format" value="'12h'"