  - name: install software
    dnf:
      name: 
        - darktable
        - vlc
        - gimp
        - snapd
      state: latest

  - name: start snapd 
    service: 
      name: snapd  
      state: started

  - name: Install snap software   
    snap: 
      name: code
      classic: yes
      become: yes
      become_method: sudo
  
  

