- name: install indi (allow erasing)
  become: yes
  command: dnf --allowerasing -y install indi-*-bleeding
  
- name: install packages
  dnf:
    name: 
      - darktable
      - gimp
      - snapd
      - indi-atik
      - kstars-bleeding
      - phd2
      - nano
    state: latest

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: reload snapd 
  systemd: 
    name: snapd  
    state: reloaded

- name: start snapd 
  systemd: 
    name: snapd  
    state: started

# need to add symlink on fedora 
- name: add snap symlink 
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: Install snap software   
  command: snap install code --classic

    
  

