- name: install packages
  dnf:
    name: 
      - 'https://download.opensuse.org/repositories/home:/lupinix-indi:/fedora-bleeding/Fedora_30/noarch/lupinix-indi-bleeding-1.0-218.7.noarch.rpm'
      - darktable
      - gimp
      - snapd
     # - "indi-*-bleeding"
     # - indi-atik
     # - kstars-bleeding
      - phd2
      - nano
    state: present

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: start snapd 
  service: 
    name: snapd  
    state: started

- name: add snap symlink 
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: Install snap software   
  command: snap install code --classic

    
  

