  - name: install software
    dnf:
      name: 
        - darktable
        - vlc
        - gimp
        - snapd
      state: latest

  - name: start snapd 
    service: 
      name: snapd  
      state: started

  - name: add snap symlink 
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      owner: root
      group: root
      state: link

  - name: Install snap software   
    command: snap install code --classic
  
  

