  - name: install software
    dnf:
      name: 
        - darktable
        - vlc
        - gimp
        - snapd
      state: latest

  - name: start snapd 
    service: 
      name: snapd  
      state: started

  - name: add snap symlink 
    command: ln -s /var/lib/snapd/snap /snap

  - name: Install snap software   
    command: snap install code --classic
  
  

