 - name: install lupinix repo
    dnf:
      name: 
        - darktable
        - vlc
        - gimp
        - "*"
    #    - 'https://download.opensuse.org/repositories/home:/lupinix-indi:/fedora-bleeding/Fedora_30/noarch/lupinix-indi-bleeding-1.0-218.7.noarch.rpm'
      state: present
    
  

