  - name: install software
    dnf:
      name: 
        - darktable
        - vlc
        - gimp
        - snapd
      state: latest
      
    snap: 
      name:
        - code
      classic: yes
  
  

